title: "ROGUEDSGNR Site"
description: "Jekyll site using hacked-jekyll theme"
baseurl: ""
url: "http://127.0.0.1:4000"

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
