title: "ROGUEDSGNR Links"
description: "ROGUEDSGNR Links and contacts for quick access"
baseurl: ""
url: "https://roguedsgnr.github.io/"

remote_theme: piazzai/hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
